var T = {
'EDITOR_EMPTY_TITLE' : '在這裡輸入暱稱',
'PROGRESS_FORCESTOP' : '停止',
'ALMOSTDONE_OK' : '確定',
'EDITOR_NO_TITLE' : '請輸入暱稱。',
'EMPTY_ERROR' : '傳回不明訊息，請再試一次。',
'ERROR' : '伺服器錯誤，請通知管理員。',
'TIMEOUT' : '連線逾時，請檢查網路連線並再試一次。',
'ADDON_SUGGEST_LIST' : '或是從下面選擇最多人在此屬性推薦的附加元件 ...',
'ADDON_SEARCH_RESULT' : '搜尋結果：',
'ADDON_ADD' : '新增',
'ADDON_DEL' : '刪除',
'ADDON_ADD_CONFIRM' : '確定',
'ADDON_CANNOT_ADD' : '無法重複新增附加元件。',
'SWFUPLOAD_ZERO_BYTE_FILE' : '檔案的大小為 0 。',
'SWFUPLOAD_FILE_EXCEEDS_SIZE_LIMIT' : '檔案超過限制大小。',
'SWFUPLOAD_INVALID_FILETYPE' : '無法接受此檔案格式。',
'EDITOR_CONFIRM_QUIT' : '離開此頁會失去所有未儲存的資料！',
'EDITOR_NOT_LOGGED_IN' : '沒有登入，無法存檔。或是請開新分頁重新登入再按一次存檔。',
'EDITOR_TITLE_LENGTH' : '名稱太長了喔！',
'EDITOR_NAME_LENGTH' : '網址太長了喔！',
'EDITOR_SAVE_NO_NAME' : '沒有提供網址，你搞笑喔？',
'EDITOR_SAVE_ERROR_TOKEN' : '認證失敗。',
'EDITOR_BAD_NAME' : '無法使用此網址作為您的推薦頁，請換一個。',
'EDITOR_SAVE_FEATURE_ERROR' : '推薦功能不是數字，你又搞笑了。',
'EDITOR_FEATURES_COUNT' : '請選三個你推薦別人使用 Firefox 的理由，三個就對了！',
'EDITOR_AVATAR_WRONG_FILE_TYPE' : '上傳的不是圖檔，無法使用。',
'EDITOR_AVATAR_SIZE_TOO_LARGE' : '上傳的檔案長寬太大了，請換小一點的圖片。'
};